<?php
$user=\App\Core\Auth::user();
$lastDeep=\App\Core\DB::one('SELECT * FROM scans WHERE project_id=? AND type="deep" AND status="completed" ORDER BY id DESC LIMIT 1',[$p['id']]);
$lastMeta=$lastDeep?(json_decode((string)($lastDeep['meta_json']??''),true)?:[]):[];
$activeMeta=!empty($activeDeep)?(json_decode((string)($activeDeep['meta_json']??''),true)?:[]):[];
$displayMeta=$activeMeta?:$lastMeta;
$scanWarnings=$_SESSION['scan_warnings']??[];unset($_SESSION['scan_warnings']);
$aiConfigured=\App\Services\AiScanService::enabled();
$catLabels=['security'=>'Security','operations'=>'Operations','code_quality'=>'Code Quality','legal_compliance'=>'Legal & Compliance'];
$groups=['critical'=>[],'high'=>[],'medium'=>[],'low'=>[],'pending'=>[],'ready'=>[],'not_applicable'=>[]];
foreach($checks as $c){if($c['status']==='ready')$groups['ready'][]=$c;elseif($c['status']==='not_applicable')$groups['not_applicable'][]=$c;elseif(in_array($c['status'],['pending','question_required'],true))$groups['pending'][]=$c;else $groups[$c['severity']][]=$c;}
$catCounts=[];foreach($catLabels as $k=>$l)$catCounts[$k]=(int)(\App\Core\DB::one('SELECT COUNT(*) c FROM checks WHERE project_id=? AND category=? AND status="need_attention"',[$p['id'],$k])['c']??0);
$activeScanId=(int)($activeDeep['id']??0);
$coverageKeys=['url'=>'URL','pages'=>'Pages','source'=>'Source','runtime'=>'Runtime','ai'=>'AI'];
$coverageState=function(string $key)use($displayMeta){$v=$displayMeta['coverage'][$key]??null;if(is_array($v))return (string)($v['state']??'none');if($v===true)return 'complete';return 'none';};
$coverageDetail=function(string $key)use($displayMeta){$v=$displayMeta['coverage'][$key]??null;return is_array($v)?(string)($v['detail']??''):'';};
$coverageClass=function(string $s){return in_array($s,['complete','fresh','connected'],true)?'ok':(in_array($s,['blocked','failed'],true)?'bad':(in_array($s,['stale','stored','skipped','disconnected','disabled','none'],true)?'limited':''));};
$lastDelta=(int)($lastMeta['score_delta']??0);
$lastBefore=is_array($lastMeta['before_summary']??null)?$lastMeta['before_summary']:[];
$lastAfter=is_array($lastMeta['after_summary']??null)?$lastMeta['after_summary']:[];
$lastReason='';
if($lastBefore&&$lastAfter){
  $rd=(int)($lastAfter['ready']??0)-(int)($lastBefore['ready']??0);
  $ad=(int)($lastAfter['need_attention']??0)-(int)($lastBefore['need_attention']??0);
  $pd=(int)($lastAfter['pending_total']??0)-(int)($lastBefore['pending_total']??0);
  $parts=[];if($rd)$parts[]=(($rd>0?'+':'').$rd).' ready';if($ad)$parts[]=(($ad>0?'+':'').$ad).' attention';if($pd)$parts[]=(($pd>0?'+':'').$pd).' pending';
  $lastReason=$parts?('Why: '.implode(' · ',$parts)):'No check-state totals changed.';
}
?>
<div class="readiness-head" data-readiness-head>
  <div class="ready-score"><span class="num" data-live-score><?=$summary['score']?></span><span class="pct">%</span><span class="word">ready</span></div>
  <div class="project-scan-actions"><span class="pill url-pill">◎ <?=h(parse_url($p['url'],PHP_URL_HOST)?:$p['url'])?></span><button class="btn" data-confirm-scan <?=$activeScanId?'disabled':''?>>↻ <span data-scan-button-label><?=$activeScanId?'Scanning…':'AI Scan again'?></span></button></div>
</div>

<div class="progressive-scan" data-scan-controller data-project-slug="<?=h($p['slug'])?>" data-active-scan-id="<?=$activeScanId?>" data-applicable="<?=(int)$summary['applicable']?>" data-csrf="<?=h(\App\Core\Csrf::token())?>" data-start-url="/builds/<?=h($p['slug'])?>/dashboard/scan/start" data-step-prefix="/builds/<?=h($p['slug'])?>/dashboard/scan/">
  <div class="scan-live-top">
    <div><strong data-scan-state><?=$activeScanId?'SCANNING…':'AI + EVIDENCE SCANNER'?></strong><span data-scan-message><?=$activeScanId?h((string)($activeMeta['message']??'Resuming evidence scan…')):($aiConfigured?'OpenAI '.h(\App\Services\OpenAIService::model()).' · evidence-gated':'AI not configured · deterministic evidence only')?></span></div>
    <div class="scan-coverage" data-scan-coverage><?php foreach($coverageKeys as $key=>$label):$st=$coverageState($key);?><span class="<?=$coverageClass($st)?>" data-coverage-key="<?=h($key)?>" data-state="<?=h($st)?>" title="<?=h($coverageDetail($key))?>"><?=h($label)?><?php if($st&&!in_array($st,['none','queued','complete'],true)):?> · <?=h(str_replace('_',' ',$st))?><?php endif?></span><?php endforeach?></div>
  </div>
  <div class="scan-linear-wrap" data-scan-linear-wrap>
    <div class="progress-track scan-linear" data-scan-track aria-label="Readiness scan progress">
      <span class="ready" data-scan-ready style="width:<?=$summary['applicable']?($summary['ready']/$summary['applicable']*100):0?>%"></span>
      <span class="attention" data-scan-attention style="width:<?=$summary['applicable']?($summary['need_attention']/$summary['applicable']*100):0?>%"></span>
      <span class="scan-reviewed" data-scan-reviewed style="width:0%"></span>
      <span class="pending" data-scan-pending style="flex:1"></span>
    </div>
    <div class="scan-linear-meta"><span data-scan-checked><?=$activeScanId?'0 of '.(int)$summary['applicable'].' checked':'Latest readiness state'?></span><span data-scan-progress><?=$activeScanId?(int)($activeMeta['progress']??1).'%':''?></span></div>
  </div>
</div>

<div class="scan-warning-box" data-scan-warning-box <?=$scanWarnings?'':'hidden'?>>
  <strong>Scan coverage notes</strong><div data-scan-warnings><?php foreach($scanWarnings as $w):?><div>• <?=h($w)?></div><?php endforeach?></div>
</div>

<div class="summary-row"><span><strong style="color:var(--teal)">● <b data-summary-ready><?=$summary['ready']?></b></strong> ready</span><span><strong style="color:var(--coral)">■ <b data-summary-attention><?=$summary['need_attention']?></b></strong> need attention</span><span><strong><b data-summary-pending><?=$summary['pending_total']?></b></strong> pending</span><?php if($lastDeep):?><span class="scan-score-delta <?=($lastDelta<0?'down':($lastDelta>0?'up':''))?>" data-score-delta><?= $lastDelta===0?'Last scan: no score change':('Last scan: '.($lastDelta>0?'+':'').$lastDelta.' points') ?></span><?php endif?></div>
<div class="scan-score-explain muted" data-score-explain <?=($lastReason||$activeScanId)?'':'hidden'?>><?=h($activeScanId?'Scan changes will be explained as evidence arrives.':$lastReason)?></div>

<section class="scan-live-results" data-scan-live-results <?=$activeScanId?'':'hidden'?>>
  <div class="issues-heading"><span class="scan-pulse"></span>LIVE SCAN RESULTS</div>
  <div class="scan-live-feed" data-scan-live-feed aria-live="polite"></div>
</section>

<div class="tabs"><a class="tab <?=$tab==='overview'?'active':''?>" href="/builds/<?=h($p['slug'])?>/dashboard/readiness/overview">Overview</a><?php foreach($catLabels as $k=>$l):?><a class="tab <?=$tab===$k?'active':''?>" href="/builds/<?=h($p['slug'])?>/dashboard/readiness/<?=$k?>"><?=h($l)?><?php if($catCounts[$k]):?><span class="badge-count"><?=$catCounts[$k]?></span><?php endif?></a><?php endforeach?></div>
<?php if(!$p['github_repo']):?><div class="banner"><span class="project-mark mini" style="background:#f3efe7;color:var(--coral)">⌁</span><div class="grow"><div class="banner-title">We found what the URL can show. Link your GitHub or upload source for deeper checks.</div><div class="muted" style="font-size:13px">Read-only GitHub scanning never changes your code.</div></div><button class="btn coral" type="button" data-modal-open="githubConnectModal">Connect code →</button></div><?php endif?>
<?php if($summary['need_attention']):?><div class="banner"><div class="grow"><strong><?=$summary['need_attention']?> items need your attention.</strong></div><button class="btn coral" data-drawer-open="finding-<?=($groups['critical'][0]['id']??$groups['high'][0]['id']??$groups['medium'][0]['id']??$groups['low'][0]['id']??0)?>">Walk through <?=min(2,$summary['need_attention'])?> items →</button></div><?php endif?>
<?php foreach(['critical'=>'CRITICAL ISSUES','high'=>'HIGH ISSUES','medium'=>'MEDIUM ISSUES','low'=>'LOW ISSUES','pending'=>'PENDING CHECKS','ready'=>'ALREADY COVERED','not_applicable'=>'NOT APPLICABLE'] as $g=>$label): ?><?php if($groups[$g]): ?><section class="issues-section"><div class="issues-heading"><span class="badge-count"><?=count($groups[$g])?></span><?=$label?></div><div class="finding-list"><?php foreach($groups[$g] as $c):?><div class="finding-row" data-check-row="<?=h($c['check_key'])?>"><div class="finding-sev"><?=($c['status']==='ready'?'✓':($g==='pending'?'◌':'△'))?></div><div><div class="finding-title"><?=h(\App\Services\ReadinessService::presentTitle($c))?></div><div class="finding-desc"><?=h(\App\Services\ReadinessService::presentDescription($c))?></div></div><a href="#" class="finding-view" data-drawer-open="finding-<?=$c['id']?>">View →</a></div><?php endforeach?></div></section><?php endif; ?><?php endforeach; ?>
<?php foreach($checks as $c):?><?php $qq=\App\Core\DB::one('SELECT * FROM quick_questions WHERE check_key=? ORDER BY id ASC LIMIT 1',[$c['check_key']]);$qopts=$qq?(json_decode((string)$qq['options_json'],true)?:[]):[];$ev=\App\Services\ReadinessService::recentEvidence((int)$c['id'],4);?><div id="finding-<?=$c['id']?>" data-drawer class="drawer-backdrop" hidden><aside class="drawer"><button class="drawer-close" data-drawer-close>×</button><div class="drawer-status"><?=h(str_replace('_',' ',$c['status']))?></div><h2><?=h(\App\Services\ReadinessService::presentTitle($c))?></h2><p><?=h(\App\Services\ReadinessService::presentDescription($c))?></p><h3>Why it matters</h3><p class="muted"><?=h($c['remediation']?:'Production evidence for this check affects reliability, security or customer trust.')?></p><h3>Evidence</h3><?php if($ev):foreach($ev as $e):?><div class="card" style="padding:12px;margin:8px 0"><strong><?=h(strtoupper($e['source']))?><?php if(isset($e['confidence'])):?> · <?=number_format((float)$e['confidence']*100,0)?>% confidence<?php endif?></strong><div class="muted"><?=h($e['summary'])?></div><?php if(!empty($e['_repeat_count'])&&$e['_repeat_count']>1):?><small class="muted">Observed <?= (int)$e['_repeat_count'] ?> times; duplicate history collapsed.</small><?php endif?></div><?php endforeach;else:?><p class="muted">No evidence collected yet.</p><?php endif?><?php if($qq):?><h3>Quick question</h3><p><strong><?=h($qq['question'])?></strong></p><form method="post" action="/builds/<?=h($p['slug'])?>/dashboard/check/<?=$c['id']?>/answer"><?=csrf()?><div style="display:grid;gap:8px"><?php foreach($qopts as $qo):?><button class="btn" name="answer" value="<?=h($qo['key']??'')?>"><?=h($qo['label']??$qo['key']??'Answer')?></button><?php endforeach?></div></form><?php endif?><div class="drawer-bottom"><button class="btn" data-drawer-close>Skip to next</button><a class="btn dark" href="/builds/<?=h($p['slug'])?>/dashboard/source">Generate / verify fix</a></div></aside></div><?php endforeach?>
<?php $githubConfigured=\App\Services\GitHubService::configured(false);?>
<div class="modal-layer" id="githubConnectModal" hidden><div class="modal-card github-connect-modal"><button class="drawer-close" type="button" data-modal-close>×</button><div class="side-label" style="padding:0">SOURCE EVIDENCE</div><h2 class="section-title" style="font-size:30px;margin:10px 0 6px">GET YOUR CODE ON GITHUB</h2><p class="muted">Connect a repository to unlock deeper Security and Code Quality checks. SIUGOALS requests read-only access and never changes your code during scanning.</p><div class="github-steps"><div><span>1</span><p><strong>Authorize SIUGOALS</strong><small>Choose the GitHub account that owns the repository.</small></p></div><div><span>2</span><p><strong>Select a repository</strong><small>You decide exactly which repository SIUGOALS can read.</small></p></div><div><span>3</span><p><strong>Run the deep scan</strong><small>Source evidence is added to Readiness and can be re-checked after fixes.</small></p></div></div><?php if($githubConfigured):?><a class="btn yellow" style="width:100%" href="/builds/<?=h($p['slug'])?>/github/connect">CONNECT CODE →</a><?php else:?><div class="setup-note">GitHub scanning is not available on this SIUGOALS installation yet. You can still run the same source scanner by uploading a ZIP project.</div><a class="btn yellow" style="width:100%" href="/builds/<?=h($p['slug'])?>/dashboard/source#zip-scan">SCAN A ZIP PROJECT →</a><?php endif?></div></div>
<div class="modal-layer" id="scanConfirm" hidden><div class="modal-card"><div class="side-label" style="padding:0">AI + EVIDENCE SCAN</div><h2 class="section-title" style="font-size:27px">RUN A FRESH READINESS SCAN?</h2><p>The scan now runs progressively. As soon as you start, SIUGOALS returns to the Readiness indicator, moves through URL → Pages → Runtime → Source → AI, and shows verified results as each phase finishes. Unsupported checks remain <strong>Pending</strong>; the scanner does not guess.</p><?php $rescanCost=tokenCost('TOKEN_COST_READINESS_RESCAN',300,(int)$p['id']);?><p><?php if($rescanCost===0):?>Owner acceptance mode is active. This validation scan will use <strong>0 tokens</strong>.<?php else:?>This re-scan costs approximately <strong><?=number_format($rescanCost)?> tokens</strong>. Your current balance is <strong><?=number_format((int)$user['token_balance']+(int)($user['bonus_tokens']??0))?></strong>.<?php endif?></p><?php if(!$aiConfigured):?><div class="setup-note">OPENAI_API_KEY is not configured. URL/source/runtime evidence still runs, but AI adjudication will be skipped.</div><?php endif?><div style="display:flex;justify-content:flex-end;gap:10px"><button class="btn" type="button" data-modal-close>Cancel</button><form method="post" action="/builds/<?=h($p['slug'])?>/dashboard/scan/start" data-progressive-scan-form><?=csrf()?><button class="btn coral" data-scan-submit>Start scan</button></form></div></div></div>
<style>
.progressive-scan{margin:12px 0 0}.scan-live-top{display:flex;justify-content:space-between;gap:18px;align-items:center;margin-bottom:8px}.scan-live-top strong{display:block;font-family:"Archivo Narrow";font-size:15px;letter-spacing:.02em}.scan-live-top>div>span{font-size:12px;color:#746a65}.scan-coverage{display:flex;gap:7px;flex-wrap:wrap;justify-content:flex-end}.scan-coverage span{border:1px solid #ddd5ce;border-radius:999px;padding:5px 8px;font-size:11px;color:#857a74;transition:.2s}.scan-coverage span.ok{border-color:#9edcd2;background:#edf9f7;color:#176f62}.scan-coverage span.bad{border-color:#f1aaa3;background:#fff1ef;color:#b62d24}.scan-coverage span.limited{border-color:#ead2a3;background:#fff8e8;color:#8f681e}.scan-linear-wrap{scroll-margin-top:16px}.scan-linear{height:11px;position:relative;overflow:hidden;--scan-phase-progress:1%}.scan-linear.scanning::before{content:"";position:absolute;left:0;top:0;bottom:0;width:var(--scan-phase-progress);background:rgba(46,74,116,.10);transition:width .55s ease;z-index:2;pointer-events:none}.scan-linear.scanning::after{content:"";position:absolute;inset:0;background:linear-gradient(90deg,transparent,rgba(255,255,255,.62),transparent);transform:translateX(-100%);animation:scanSweep 1.3s linear infinite;z-index:3;pointer-events:none}.scan-reviewed{display:block;background:#d7d0ca;height:100%;transition:width .45s ease}.progress-track>span{transition:width .45s ease}.scan-linear-meta{display:flex;justify-content:space-between;font-size:12px;color:#857a74;margin-top:5px}.scan-live-results{margin:18px 0}.scan-live-feed{display:grid;gap:6px}.scan-live-item{display:grid;grid-template-columns:22px 1fr auto;gap:10px;align-items:start;padding:10px 12px;border:1px solid var(--border);background:#fff}.scan-live-item .state{font-weight:800}.scan-live-item.ready .state{color:var(--teal)}.scan-live-item.need_attention .state{color:var(--coral)}.scan-live-item.pending .state{color:#9a8e87}.scan-live-item small{color:#8b8079}.finding-row.scan-updated{outline:2px solid rgba(53,180,158,.22);outline-offset:-2px;background:#fbfffe;transition:background .25s,outline-color .25s}.scan-pulse{display:inline-block;width:7px;height:7px;border-radius:50%;background:var(--teal);margin-right:7px;animation:scanPulse 1s ease-in-out infinite}.scan-score-delta{margin-left:auto;font-size:12px;color:#857a74}.scan-score-explain{font-size:12px;margin:-4px 0 12px}.scan-score-delta.down{color:var(--coral)}.scan-score-delta.up{color:var(--teal)}.scan-warning-box{margin:10px 0 16px;padding:12px 14px;border:1px solid #e7c98d;background:#fff8e8;border-radius:12px;font-size:13px}.scan-warning-box strong{display:block;margin-bottom:5px}@keyframes scanSweep{to{transform:translateX(100%)}}@keyframes scanPulse{50%{opacity:.28}}@media(max-width:720px){.scan-live-top{align-items:flex-start;flex-direction:column}.scan-coverage{justify-content:flex-start}.scan-score-delta{width:100%;margin-left:0}}
@media(prefers-reduced-motion:reduce){.scan-linear.scanning::after,.scan-pulse{animation:none}}
.modal-layer{position:fixed;inset:0;background:rgba(0,0,0,.2);z-index:120;display:grid;place-items:center;padding:20px}.modal-layer[hidden]{display:none}.modal-card{width:min(460px,100%);background:#fff;border:1px solid var(--border);border-radius:16px;padding:24px;box-shadow:0 15px 40px rgba(0,0,0,.16)}
</style>
