<?php
$cycleKey=date('Y-m');
$pending=array_values(array_filter($refs,fn($r)=>$r['status']==='pending'));
$activatedAll=array_values(array_filter($refs,fn($r)=>$r['status']==='activated'));
$activated=array_values(array_filter($activatedAll,fn($r)=>($r['reward_cycle_key']??'')===$cycleKey));
?>
<div class="account-title"><h1><?=h(t('Referrals'))?></h1><p>Invite peer builders. Both of you earn tokens.</p></div>
<div class="billing-card"><h3>Your invite link</h3><p class="muted">Share this with builders you trust.</p><div class="copy-field"><input readonly id="ref-url" value="<?=h(\App\Core\Util::baseUrl().'/signup?ref='.$user['referral_code'])?>"><button type="button" class="icon-btn" data-copy="ref-url" aria-label="Copy invite link">⧉</button></div></div>
<div class="billing-card"><div class="ref-cycle-layout"><div><h3>This cycle's referrals</h3><p class="muted">Activated when a peer completes their first scan.</p></div><div class="ref-count"><?=count($activated)?> / 5 <small>used</small></div></div><div class="referral-progress"><?php for($i=0;$i<5;$i++):?><span class="<?=$i<count($activated)?'filled':''?>"></span><?php endfor?></div></div>
<div class="billing-card"><h3>How it works</h3><ol class="how-list"><li>Share your invite link with a peer builder.</li><li>They sign up and start with 1,500 tokens (500 bonus).</li><li>They run their first scan. You earn +1,000 tokens.</li><li>Cap: 5 rewarded referrals per billing cycle.</li></ol></div>
<div class="billing-card"><h3>Pending <span class="badge-count"><?=count($pending)?></span></h3><p class="muted">Peers who signed up but haven't scanned yet.</p><?php if(!$pending):?><div class="account-empty">No pending referrals. When a peer uses your link, they'll appear here.</div><?php else:foreach($pending as $r):?><div class="referral-row"><div><strong><?=h($r['name']?:$r['email'])?></strong><small><?=h($r['email'])?></small></div><time><?=h($r['created_at'])?></time></div><?php endforeach;endif?></div>
<div class="billing-card"><h3>Activated <span class="badge-count"><?=count($activatedAll)?></span></h3><p class="muted">Peers who completed their first scan. Rewarded referrals show their activation cycle.</p><?php if(!$activatedAll):?><div class="account-empty">No activated referrals yet. Invite a peer and they'll appear here after their first scan.</div><?php else:foreach($activatedAll as $r):?><div class="referral-row"><div><strong><?=h($r['name']?:$r['email'])?></strong><small><?=h($r['email'])?></small></div><time><?=h($r['activated_at'])?> · <?=h($r['reward_cycle_key']?:'legacy')?></time></div><?php endforeach;endif?></div>
