const BASE = new URL(import.meta.url).origin;
function uid(){return crypto.randomUUID?.() || ([1e7]+-1e3+-4e3+-8e3+-1e11).replace(/[018]/g,c=>(c^crypto.getRandomValues(new Uint8Array(1))[0]&15>>c/4).toString(16));}
function detect(){const ua=navigator.userAgent;const os=/Windows/i.test(ua)?'Windows':/Mac OS X|Macintosh/i.test(ua)?'Mac OS X':/Android/i.test(ua)?'Android':/iPhone|iPad/i.test(ua)?'iOS':/Linux/i.test(ua)?'Linux':'Unknown';const browser=/HeadlessChrome/i.test(ua)?'HeadlessChrome':/Edg\//.test(ua)?'Edge':/Chrome\//.test(ua)?'Chrome':/Firefox\//.test(ua)?'Firefox':/Safari\//.test(ua)?'Safari':'Unknown';const device=/Mobi|Android|iPhone/i.test(ua)?'Mobile':'Desktop';return{os,browser,device};}
function safeUrl(value){if(!value)return'';try{const u=new URL(String(value),location.href);u.hash='';u.search='';return u.toString().slice(0,1000)}catch(_){return String(value).split(/[?#]/)[0].slice(0,1000)}}
function safeEndpoint(value){try{const u=new URL(String(value),location.href);return `${u.origin}${u.pathname}`.slice(0,700)}catch(_){return''}}
function sanitizeText(value,max=1000){let s=String(value??'').slice(0,max);s=s.replace(/\bsk-[A-Za-z0-9_-]{16,}\b/g,'[redacted-key]').replace(/\bAKIA[0-9A-Z]{16}\b/g,'[redacted-key]').replace(/AIza[0-9A-Za-z\-_]{30,}/g,'[redacted-key]').replace(/\bBearer\s+[A-Za-z0-9._~+/=-]{12,}/gi,'Bearer [redacted]').replace(/\beyJ[A-Za-z0-9_-]{12,}\.[A-Za-z0-9_-]{8,}(?:\.[A-Za-z0-9_-]{8,})?\b/g,'[redacted-token]').replace(/((?:postgres(?:ql)?|mysql|mongodb(?:\+srv)?)\:\/\/[^:\s/]+:)[^@\s/]+@/gi,'$1[redacted]@').replace(/([?&](?:token|key|code|secret|password|pass|auth|session|signature)=)[^\s&#]+/gi,'$1[redacted]').replace(/[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}/gi,'[redacted-email]');return s;}
function sanitizeValue(v,seen=new WeakSet(),depth=0,key=''){if(v==null)return v;if(typeof v==='string'){const max=/html/i.test(key)?90000:/stack/i.test(key)?12000:/message|error/i.test(key)?4000:1000;return sanitizeText(v,max)}if(typeof v==='number')return Number.isFinite(v)?v:null;if(typeof v==='boolean')return v;if(depth>=8)return'[truncated]';if(Array.isArray(v))return v.slice(0,30).map(x=>sanitizeValue(x,seen,depth+1,key));if(typeof v==='object'){if(seen.has(v))return'[circular]';seen.add(v);const o={};for(const [k,x] of Object.entries(v).slice(0,80)){if(/password|token|cookie|authorization|secret|credit|card|value|request.?body|response.?body/i.test(k))o[k]='[redacted]';else o[k]=sanitizeValue(x,seen,depth+1,k);}return o;}return sanitizeText(v);}
function safeTarget(el){if(!el||!el.tagName)return null;return{tag:el.tagName.toLowerCase(),id:(el.id||'').slice(0,80),cls:(typeof el.className==='string'?el.className:'').slice(0,120),role:(el.getAttribute?.('role')||'').slice(0,50),name:(el.getAttribute?.('name')||'').slice(0,80),type:(el.getAttribute?.('type')||'').slice(0,50)};}
function sanitizeDOM(){const clone=document.documentElement.cloneNode(true);clone.querySelectorAll('script,style,noscript,link,base,iframe,object,embed,video,audio,source,track,portal').forEach(n=>n.remove());clone.querySelectorAll('input,textarea,select,[contenteditable]').forEach(n=>{n.removeAttribute('value');if('value' in n)n.value='';n.textContent='';n.setAttribute('data-siugoals-masked','true');});clone.querySelectorAll('[data-private],[data-mask],[data-no-record]').forEach(n=>{n.innerHTML='[masked]';});clone.querySelectorAll('*').forEach(n=>{for(const attr of [...n.attributes]){const name=attr.name.toLowerCase();if(name.startsWith('on')||['href','src','srcset','action','poster','data','xlink:href'].includes(name))n.removeAttribute(attr.name);else if(/^(?:value|srcdoc|nonce)$|password|token|secret|authorization|cookie|credit|card/i.test(name))n.setAttribute(attr.name,'[masked]');}});let html=clone.outerHTML.slice(0,80000);html=sanitizeText(html,80000).replace(/\b(?:\+?\d[\d ()-]{7,}\d)\b/g,'[masked-number]');return '<!doctype html>'+html;}
function emitDiagnostic(diag,state,details={},warn=false){
  diag.state=state;diag.updatedAt=new Date().toISOString();diag.details=sanitizeValue(details);diag.history.push({state,at:diag.updatedAt,details:diag.details});if(diag.history.length>20)diag.history=diag.history.slice(-20);
  window.SIUGOALS_DIAGNOSTICS=diag;
  try{window.dispatchEvent(new CustomEvent('siugoals:status',{detail:{state,details:diag.details}}));}catch(_){}
  const fn=warn?'warn':'info';try{console[fn](`[SIUGOALS] ${state}`,diag.details||'');}catch(_){}
}
async function responseError(r,fallback){let j=null;try{j=await r.clone().json()}catch(_){}return{code:j?.code||fallback,error:j?.error||`HTTP ${r.status}`,status:r.status,expectedOrigin:j?.expectedOrigin||null};}

export async function init({buildSlug}={}){
 if(window.SIUGOALS?.__initialized){if(window.SIUGOALS.project!==String(buildSlug||''))throw new Error('SIUGOALS is already initialized with a different project key');const live=window.SIUGOALS.status?.().state==='CONNECTED';return{ok:live,code:live?'ALREADY_INITIALIZED':'HEARTBEAT_NOT_CONFIRMED',identify:window.SIUGOALS.identify,status:window.SIUGOALS.status};}
 const diag={sdkVersion:'5.5.0',base:BASE,buildSlug:String(buildSlug||''),pageOrigin:location.origin,state:'initializing',updatedAt:new Date().toISOString(),details:{},history:[]};
 window.SIUGOALS_DIAGNOSTICS=diag;
 if(!buildSlug){emitDiagnostic(diag,'BUILD_SLUG_MISSING',{message:'Use the exact project key shown by SIUGOALS.'},true);throw new Error('SIUGOALS buildSlug is required');}
 emitDiagnostic(diag,'SDK_LOADED',{buildSlug,pageOrigin:location.origin});
 let cfg;
 try{
   const r=await fetch(`${BASE}/api/runtime/config?buildSlug=${encodeURIComponent(buildSlug)}`,{credentials:'omit',mode:'cors'});
   if(!r.ok){const e=await responseError(r,'CONFIG_REJECTED');emitDiagnostic(diag,e.code,{httpStatus:e.status,message:e.error,expectedOrigin:e.expectedOrigin},true);return{ok:false,code:e.code,diagnostics:diag};}
   cfg=await r.json();
 }catch(err){emitDiagnostic(diag,'SDK_CONFIG_FETCH_FAILED',{message:String(err?.message||'Could not load SIUGOALS runtime config.'),hint:'Check SDK CORS/network access and that https://siugoals.com is reachable from this page.'},true);return{ok:false,code:'SDK_CONFIG_FETCH_FAILED',diagnostics:diag};}
 if(!cfg?.ok||!cfg?.ingest){emitDiagnostic(diag,'SDK_CONFIG_INVALID',{message:'SIUGOALS returned an incomplete runtime configuration.'},true);return{ok:false,code:'SDK_CONFIG_INVALID',diagnostics:diag};}
 emitDiagnostic(diag,'CONFIG_OK',{project:cfg.project,expectedOrigin:cfg.expectedOrigin||null});
 const storageKey=`siugoals:${buildSlug}:sid`;let sid=sessionStorage.getItem(storageKey);if(!sid){sid=uid();sessionStorage.setItem(storageKey,sid);}const anonKey=`siugoals:${buildSlug}:anon`;let anon=localStorage.getItem(anonKey);if(!anon){anon=uid();localStorage.setItem(anonKey,anon);}const env=detect();let flags=cfg.flags||{};let ended=false;let clickHistory=[],errorTimes=[],lastErrorAt=0;const dirtyForms=new Map();let heartbeatFailures=0,domMutationVersion=0;const webVitals={lcpMs:null,cls:0,inpMs:null};
 const activityObserver=new MutationObserver(()=>{domMutationVersion++});if(document.documentElement)activityObserver.observe(document.documentElement,{subtree:true,childList:true,attributes:true,characterData:true});
 try{if(window.PerformanceObserver){if(PerformanceObserver.supportedEntryTypes?.includes('largest-contentful-paint'))new PerformanceObserver(list=>{const entries=list.getEntries();if(entries.length)webVitals.lcpMs=Math.round(entries.at(-1).startTime)}).observe({type:'largest-contentful-paint',buffered:true});if(PerformanceObserver.supportedEntryTypes?.includes('layout-shift'))new PerformanceObserver(list=>{for(const entry of list.getEntries())if(!entry.hadRecentInput)webVitals.cls=Math.round((webVitals.cls+entry.value)*1000)/1000}).observe({type:'layout-shift',buffered:true});if(PerformanceObserver.supportedEntryTypes?.includes('event'))new PerformanceObserver(list=>{for(const entry of list.getEntries())if(entry.interactionId&&(!webVitals.inpMs||entry.duration>webVitals.inpMs))webVitals.inpMs=Math.round(entry.duration)}).observe({type:'event',buffered:true,durationThreshold:40});}}catch(_){}
 async function send(type,data={}){
   if(ended&&type!=='session_end')return false;
   const payload=sanitizeValue({buildSlug,sessionId:sid,anonymousId:anon,type,url:safeUrl(location.href),...env,...data});
   try{
     const r=await fetch(cfg.ingest,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload),keepalive:true,credentials:'omit',mode:'cors'});
     if(!r.ok){if(type==='heartbeat'){heartbeatFailures++;const e=await responseError(r,'INGEST_REJECTED');emitDiagnostic(diag,e.code,{httpStatus:e.status,message:e.error,expectedOrigin:e.expectedOrigin,heartbeatFailures},true);}return false;}
     const j=await r.json().catch(()=>null);if(j?.flags)flags=j.flags;
     if(type==='heartbeat'){heartbeatFailures=0;if(diag.state!=='CONNECTED')emitDiagnostic(diag,'CONNECTED',{buildSlug,sessionId:sid,heartbeat:'accepted'});}
     return true;
   }catch(err){if(type==='heartbeat'){heartbeatFailures++;emitDiagnostic(diag,'HEARTBEAT_NETWORK_FAILED',{message:String(err?.message||'Runtime heartbeat failed.'),heartbeatFailures},true);}return false;}
 }
 function beacon(type,data={}){try{navigator.sendBeacon?.(cfg.ingest,new Blob([JSON.stringify(sanitizeValue({buildSlug,sessionId:sid,anonymousId:anon,type,url:safeUrl(location.href),...env,...data}))],{type:'text/plain;charset=UTF-8'}));}catch(_){} }
 function snapshot(reason='periodic'){if(flags.sessionReplay)send('snapshot',{meta:{html:sanitizeDOM(),reason,title:document.title.slice(0,200)}});}
 function recordError(message,stack='',meta={}){const now=Date.now();lastErrorAt=now;errorTimes=errorTimes.filter(t=>now-t<10000);errorTimes.push(now);send('error',{message,stack,meta});if(errorTimes.length>=3){send('signal',{signal:'error_cascade',meta:{count:errorTimes.length,windowMs:10000}});errorTimes=[];}}
 window.SIUGOALS={
   __initialized:true,project:String(buildSlug),
   identify(identity){if(!identity||(!identity.id&&!identity.email))return;send('identify',{identity:{id:String(identity.id||'').slice(0,190),email:String(identity.email||'').slice(0,190),name:String(identity.name||'').slice(0,190)}})},
   event(name,meta={}){send('signal',{signal:String(name).slice(0,80),meta})},flags:()=>({...flags}),status:()=>({...diag,history:[...diag.history]}),
   async access(){try{const r=await fetch(`${BASE}/api/runtime/access`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({buildSlug,sessionId:sid}),credentials:'omit',mode:'cors'});return await r.json()}catch(_){return{ok:false,active:false}}}
 };
 const firstHeartbeat=await send('heartbeat');
 send('pageview',{meta:{title:document.title.slice(0,200),referrer:safeUrl(document.referrer)}});
 setTimeout(()=>{try{const nav=performance.getEntriesByType('navigation')[0],paint=performance.getEntriesByName('first-contentful-paint')[0];if(nav)send('signal',{signal:'performance_sample',meta:{ttfbMs:Math.round(Math.max(0,nav.responseStart-nav.requestStart)),domInteractiveMs:Math.round(nav.domInteractive),loadMs:Math.round(nav.loadEventEnd||nav.duration),fcpMs:paint?Math.round(paint.startTime):null,lcpMs:webVitals.lcpMs,cls:webVitals.cls,inpMs:webVitals.inpMs,transferBytes:Number(nav.transferSize||0)}})}catch(_){}},5000);
 setInterval(()=>send('heartbeat'),30000);
 if(flags.sessionReplay){snapshot('initial');setInterval(()=>snapshot('periodic'),30000);}
 const origPush=history.pushState;history.pushState=function(...a){const r=origPush.apply(this,a);queueMicrotask(()=>{send('pageview',{meta:{navigation:'pushState'}});snapshot('navigation')});return r};addEventListener('popstate',()=>{send('pageview',{meta:{navigation:'popstate'}});snapshot('navigation')});
 if(flags.errorCapture){addEventListener('error',e=>recordError(e.message||'JavaScript error',e.error?.stack||'',{filename:safeUrl(e.filename),lineno:e.lineno,colno:e.colno}));addEventListener('unhandledrejection',e=>recordError(String(e.reason?.message||e.reason||'Unhandled promise rejection'),String(e.reason?.stack||'')));const of=window.fetch;window.fetch=async function(...a){const input=a[0],endpoint=safeEndpoint(input?.url||input),method=String(a[1]?.method||input?.method||'GET').toUpperCase().slice(0,12),internal=endpoint.startsWith(`${BASE}/api/runtime/`);try{const r=await of.apply(this,a);if(!r.ok&&!internal)send('network_error',{message:`HTTP ${r.status} ${method} ${endpoint}`,meta:{method,endpoint,status:r.status}});return r}catch(err){if(!internal)send('network_error',{message:`Network request failed ${method} ${endpoint}`,meta:{method,endpoint,error:String(err?.message||'request failed')}});throw err}};}
 if(flags.errorCapture&&window.XMLHttpRequest){const open=XMLHttpRequest.prototype.open,originalSend=XMLHttpRequest.prototype.send;XMLHttpRequest.prototype.open=function(method,url,...rest){this.__siugoalsRequest={method:String(method||'GET').toUpperCase().slice(0,12),endpoint:safeEndpoint(url)};return open.call(this,method,url,...rest)};XMLHttpRequest.prototype.send=function(...args){const request=this.__siugoalsRequest||{method:'GET',endpoint:''},internal=request.endpoint.startsWith(`${BASE}/api/runtime/`);this.addEventListener('load',()=>{if(!internal&&this.status>=400)send('network_error',{message:`HTTP ${this.status} ${request.method} ${request.endpoint}`,meta:{...request,status:this.status}})},{once:true});this.addEventListener('error',()=>{if(!internal)send('network_error',{message:`Network request failed ${request.method} ${request.endpoint}`,meta:request})},{once:true});return originalSend.apply(this,args)};}
 document.addEventListener('click',e=>{const el=e.target?.closest?.('button,[role="button"],a,input');const t=safeTarget(e.target);send('click',{meta:{target:t}});const key=JSON.stringify(t),now=Date.now();if(key===clickHistory.at(-1)?.key&&now-clickHistory.at(-1).time<700){clickHistory.push({key,time:now});clickHistory=clickHistory.filter(x=>now-x.time<2200);if(clickHistory.length>=3){send('signal',{signal:'rage_click',meta:{target:t}});clickHistory=[];}}else clickHistory=[{key,time:now}];if(el&&!el.disabled&&el.getAttribute?.('aria-disabled')!=='true'&&!el.closest?.('form')&&el.tagName!=='A'&&el.tagName!=='INPUT'){const version=domMutationVersion,url=location.href,state=`${el.getAttribute?.('aria-expanded')||''}|${el.getAttribute?.('aria-pressed')||''}|${el.className||''}`;setTimeout(()=>{const nextState=`${el.getAttribute?.('aria-expanded')||''}|${el.getAttribute?.('aria-pressed')||''}|${el.className||''}`;if(location.href===url&&domMutationVersion===version&&nextState===state)send('signal',{signal:'dead_click',meta:{target:safeTarget(el)}});},1200);}},true);
 document.addEventListener('pointerdown',e=>{const el=e.target?.closest?.('button,input,a,[role="button"]');if(el&&(el.disabled||el.getAttribute('aria-disabled')==='true'))send('signal',{signal:'dead_click',meta:{target:safeTarget(el)}});},true);
 document.addEventListener('input',e=>{const f=e.target?.form;if(f&&!/password|hidden|credit|card/i.test(e.target?.type||''))dirtyForms.set(f,{changedAt:Date.now(),submitted:false});},true);
 document.addEventListener('submit',e=>{const f=e.target;if(dirtyForms.has(f))dirtyForms.set(f,{...dirtyForms.get(f),submitted:true});},true);
 let scrollTimer;addEventListener('scroll',()=>{clearTimeout(scrollTimer);scrollTimer=setTimeout(()=>send('scroll',{meta:{x:Math.round(scrollX),y:Math.round(scrollY)}}),500)},{passive:true});
 if(flags.sessionReplay){const mo=new MutationObserver(ms=>{const summary=ms.slice(0,25).map(m=>({type:m.type,target:safeTarget(m.target),added:m.addedNodes?.length||0,removed:m.removedNodes?.length||0,attribute:m.attributeName||null}));send('mutation',{meta:{mutations:summary}})});mo.observe(document.documentElement,{subtree:true,childList:true,attributes:true,attributeFilter:['class','hidden','aria-expanded','data-state']});}
 if(flags.trustBadge){const b=document.createElement('a');b.href=`${BASE}/builds/${encodeURIComponent(buildSlug)}/trust`;b.target='_blank';b.rel='noopener';b.textContent='✓ Runs on SIUGOALS';Object.assign(b.style,{position:'fixed',right:'14px',bottom:'14px',zIndex:'2147483646',background:'#fff',color:'#201e21',border:'1px solid #e6ded8',borderRadius:'10px',padding:'8px 11px',font:'600 12px system-ui',boxShadow:'0 4px 14px rgba(0,0,0,.12)',textDecoration:'none'});document.body.appendChild(b);}
 addEventListener('pagehide',()=>{for(const [form,state] of dirtyForms){if(!state.submitted)beacon('signal',{signal:'form_abandonment',meta:{form:{id:form.id||'',action:safeUrl(form.action).slice(0,300)}}});}if(lastErrorAt&&Date.now()-lastErrorAt<15000)beacon('signal',{signal:'error_then_exit',meta:{afterMs:Date.now()-lastErrorAt}});ended=true;activityObserver.disconnect();beacon('session_end');});
 return{ok:firstHeartbeat,code:firstHeartbeat?'CONNECTED':'HEARTBEAT_NOT_CONFIRMED',identify:window.SIUGOALS.identify,status:window.SIUGOALS.status};
}
